import Link from 'next/link';
import styles from '../legal.module.css';

export const metadata = {
  title: 'Terms of Service - NeuroQuest Academy',
  description: 'Terms of service for NeuroQuest Academy educational platform',
};

export default function TermsOfServicePage() {
  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <Link href="/dashboard" className={styles.backLink}>
          <span className={styles.backIcon}>←</span>
          Back to Dashboard
        </Link>
        <h1>Terms of Service</h1>
        <p className={styles.lastUpdated}>Last updated: May 5, 2026</p>
      </div>

      <div className={styles.content}>
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using NeuroQuest Academy ("the Platform"), you agree to be bound 
            by these Terms of Service ("Terms"). If you are using the Platform on behalf of 
            a student, you represent that you are authorized to accept these Terms.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            NeuroQuest Academy is an AI-powered educational platform that provides:
          </p>
          <ul>
            <li>Adaptive learning experiences aligned with IB/MYP curriculum</li>
            <li>Personalized lesson generation using AI (Gemma, Gemini)</li>
            <li>Interactive 3D learning environments</li>
            <li>Progress tracking for students, teachers, and parents</li>
            <li>Real-time AI tutoring and feedback</li>
          </ul>
        </section>

        <section>
          <h2>3. User Accounts</h2>
          <h3>3.1 Eligibility</h3>
          <p>
            The Platform is designed for educational institutions, teachers, parents, and 
            students (Grades 1-12). Users under 13 require parental consent.
          </p>

          <h3>3.2 Account Responsibilities</h3>
          <ul>
            <li>Keep login credentials secure and confidential</li>
            <li>Notify us immediately of unauthorized access</li>
            <li>Accept responsibility for all activities under your account</li>
            <li>Use accurate information when registering</li>
          </ul>
        </section>

        <section>
          <h2>4. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul>
            <li>Use the Platform for any illegal purpose</li>
            <li>Attempt to bypass security or access controls</li>
            <li>Share account credentials inappropriately</li>
            <li>Upload malicious code or content</li>
            <li>Use AI features to generate harmful or inappropriate content</li>
            <li>Reverse engineer the Platform or its AI components</li>
          </ul>
        </section>

        <section>
          <h2>5. Educational Purpose</h2>
          <p>
            NeuroQuest is an educational tool. While we encourage exploration and creativity, 
            the Platform and its AI-generated content are intended solely for learning purposes. 
            We do not guarantee specific academic outcomes.
          </p>
        </section>

        <section>
          <h2>6. Intellectual Property</h2>
          <ul>
            <li><strong>User Content:</strong> Students retain rights to content they create; grant us license to use for service improvement</li>
            <li><strong>Platform Content:</strong> NDN Analytics owns the Platform, branding, and AI-generated learning materials</li>
            <li><strong>Third-Party:</strong> Google AI services used under Google&apos;s applicable terms</li>
          </ul>
        </section>

        <section>
          <h2>7. AI-Generated Content</h2>
          <p>
            Content generated by our AI (lessons, explanations, questions) is created 
            dynamically and may not always be accurate. We strive for quality but cannot 
            guarantee completeness. Teachers should review AI content before use with students.
          </p>
        </section>

        <section>
          <h2>8. Fees and Payments</h2>
          <p>
            School pilots may be offered at no cost. Paid subscriptions (if any) will be 
            clearly communicated. Refunds subject to our refund policy communicated at purchase.
          </p>
        </section>

        <section>
          <h2>9. Data and Privacy</h2>
          <p>
            Your use of the Platform is also governed by our <Link href="/legal/privacy-policy">Privacy Policy</Link>. 
            By using the Platform, you consent to data collection and processing as described 
            in the Privacy Policy, including AI processing of student data.
          </p>
        </section>

        <section>
          <h2>10. Disclaimer of Warranties</h2>
          <p>
            THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. 
            WE DO NOT GUARANTEE:
          </p>
          <ul>
            <li>Uninterrupted or error-free operation</li>
            <li>Specific learning outcomes or grade improvements</li>
            <li>Accuracy of all AI-generated content</li>
            <li>Compatibility with all devices and browsers</li>
          </ul>
        </section>

        <section>
          <h2>11. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, NDN Analytics shall not be liable for 
            indirect, incidental, special, or consequential damages arising from Platform use. 
            Our total liability shall not exceed amounts paid by you (if any) in the past 12 months.
          </p>
        </section>

        <section>
          <h2>12. Indemnification</h2>
          <p>
            You agree to indemnify NDN Analytics against claims arising from your violation 
            of these Terms or misuse of the Platform.
          </p>
        </section>

        <section>
          <h2>13. Termination</h2>
          <p>
            We may suspend or terminate accounts that violate these Terms. You may terminate 
            your account at any time by contacting us. Upon termination, we may retain certain 
            data as required by law or for legitimate educational records.
          </p>
        </section>

        <section>
          <h2>14. Changes to Terms</h2>
          <p>
            We may modify these Terms. Material changes will be communicated via email or 
            Platform notification. Continued use after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2>15. Governing Law</h2>
          <p>
            These Terms are governed by the laws of the United Arab Emirates (UAE). 
            Disputes shall be subject to the exclusive jurisdiction of UAE courts.
          </p>
        </section>

        <section>
          <h2>16. Contact</h2>
          <p>
            <strong>NDN Analytics (NeuroQuest)</strong><br />
            Email: <a href="mailto:legal@ndnanalytics.com">legal@ndnanalytics.com</a><br />
            Website: <a href="https://www.ndnanalytics.com" target="_blank" rel="noopener noreferrer">www.ndnanalytics.com</a>
          </p>
        </section>
      </div>
    </div>
  );
}
